### ISSUE TITLE
Error searching on scihub using eodag 2.8

### ISSUE THREAD

**Issue by TGrmn** [CS-SI/eodag-sentinelsat#37]
**Describe the bug**
Error when searching on scihub using eodag 2.8

**Code To Reproduce**

```py
from eodag import EODataAccessGateway
dag= EODataAccessGateway()
dag.set_preferred_provider("scihub")
dag.search(
    productType='S2_MSI_L1C',
    geom={'lonmin': 1, 'latmin': 43.5, 'lonmax': 2, 'latmax': 44},
    start='2021-01-01',
    end='2021-01-15'
)
```

**Output**
```
Error while searching on provider scihub (ignored):
Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.10/site-packages/eodag/api/core.py", line 1389, in _do_search
    res, nb_res = search_plugin.query(count=count, **kwargs)
  File "/home/thomas/.local/lib/python3.10/site-packages/eodag_sentinelsat/eodag_sentinelsat.py", line 107, in query
    query_params, provider_product_type = self._update_keyword(**kwargs)
  File "/home/thomas/.local/lib/python3.10/site-packages/eodag_sentinelsat/eodag_sentinelsat.py", line 445, in _update_keyword
    provider_product_type = self.map_product_type(product_type, **kwargs)
TypeError: QueryStringSearch.map_product_type() got an unexpected keyword argument 'auth'
([], 0)
```

**Environment:**
 - Python version: 3.10.6
 - EODAG version: 2.8
 - eodag-sentinelsat version: 0.4.1

**Additional context**
eodag-sentinelsat plugin works fine with eodag 2.6.2 and 2.7 (did not check with other versions)

**Comment by sbrunato** [comment]
Hello @TGrmn , thanks for submitting this issue, we'll check it soon and apply a fix if needed
